# Generated by Django 5.1.5 on 2025-01-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_fruit_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='type',
            field=models.CharField(default='fruit', max_length=100),
        ),
    ]
