# Generated by Django 5.1.5 on 2025-01-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_fruit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='type',
            field=models.CharField(default='false', max_length=100),
        ),
    ]
