# Generated by Django 5.1.5 on 2025-01-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_car_toyota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ManyToManyField(to='Home.toyota', verbose_name='related toyota')),
            ],
        ),
    ]
