# Generated by Django 5.1.5 on 2025-02-04 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_manufacturerofcars_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='manufacturer',
        ),
        migrations.DeleteModel(
            name='ManufacturerOfCars',
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
