# Generated by Django 5.1.5 on 2025-02-04 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_human'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Human',
        ),
    ]
