# Generated by Django 5.1.5 on 2025-02-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_delete_human'),
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
            ],
        ),
    ]
