# Generated by Django 5.1.5 on 2025-02-04 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_reporter_articles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['headline']},
        ),
    ]
