# Generated by Django 5.1.5 on 2025-02-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.TextField()),
            ],
        ),
    ]
