# Generated by Django 5.1.5 on 2025-02-04 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_alter_articles_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='reporters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.reporter'),
        ),
    ]
