# Generated by Django 5.1.5 on 2025-02-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_blogsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('group', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
