# Generated by Django 5.1.5 on 2025-02-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_groups_persons_membership_groups_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='members',
            field=models.ManyToManyField(through='Home.Membership', to='Home.persons'),
        ),
    ]
