# Generated by Django 5.1.5 on 2025-02-05 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_alter_students_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['age']},
        ),
    ]
