# Generated by Django 5.1.5 on 2025-02-04 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_alter_groups_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='articles',
            name='reporters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.reporter'),
        ),
    ]
