# Generated by Django 5.1.5 on 2025-02-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_alter_students_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='classname',
            field=models.CharField(default='value', max_length=90),
        ),
        migrations.AlterField(
            model_name='students',
            name='group',
            field=models.CharField(max_length=50, verbose_name='groups'),
        ),
    ]
